/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.vet;

import edu.vet.boundary.VeterinarioBoundary;
import javafx.application.Application;

public class App {
    public String getGreeting() {
        return "Pet Shop Aula 13";
    }

    public static void main(String[] args) {
        Application.launch(VeterinarioBoundary.class, args);
    }
}
